### ISSUE TITLE
onUploadImage throws error

### ISSUE THREAD

**Issue by ketys-from-meiro** [zalify/easy-email#164]
I'm trying to play with the interface and was curious how image upload is handled but it throws error when I try to upload some image.

I've just made a simple testing function like this:
```
const onUploadImage = async (blob: Blob) => {
    //TODO: validation, compression etc?
    const unused = await api.systemInfo.get()
    return "https://public-domain.com/public-image.jpg"
  }
  ```
  
  but it completely removes image element from the editor and throws:
  ```
  index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:258285:20
    at div
    at Item (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:204928:24)
    at div
    at Stack2 (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:204937:24)
    at div
    at div
    at Transition2 (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:214543:30)
    at div
    at Item$3 (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:234946:78)
    at div
    at Collapse (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:235124:68)
    at div
    at div
    at Space (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:248790:68)
    at CollapseWrapper (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:259861:99)
    at div
    at div
    at AttributesPanelWrapper (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:259186:87)
    at Image$1 (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:260553:94)
console.<computed> @ index.js:1
push../node_modules/easy-email-editor/lib/index.js.console.error @ HtmlStringToReactNodes.tsx:36
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
warnAboutUpdateOnUnmountedFiberInDEV @ react-dom.development.js:23914
scheduleUpdateOnFiber @ react-dom.development.js:21840
dispatchAction @ react-dom.development.js:16139
(anonymous) @ index2.js:36032
(anonymous) @ index2.js:34005
(anonymous) @ index2.js:33897
_callee3$ @ index2.js:33897
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
fulfilled @ index2.js:41
Promise.then (async)
step @ index2.js:53
(anonymous) @ index2.js:54
__async @ index2.js:38
uploadFiles @ index2.js:33878
_callee5$ @ index2.js:33956
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
(anonymous) @ index2.js:54
__async @ index2.js:38
el.onchange @ index2.js:33948


index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at ImageUploader (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:255741:98)
    at div
    at Col$1 (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:243333:68)
    at div
    at Row$1 (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:243490:68)
    at div
    at div
    at Space (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:248790:68)
    at Control2 (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:243687:24)
    at Item$2 (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:244192:68)
    at Field (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:479645:26)
    at http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:258285:20
    at div
    at Item (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:204928:24)
    at div
    at Stack2 (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:204937:24)
    at div
    at div
    at Transition2 (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:214543:30)
    at div
    at Item$3 (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:234946:78)
    at div
    at Collapse (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:235124:68)
    at div
    at div
    at Space (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:248790:68)
    at CollapseWrapper (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:259861:99)
    at div
    at div
    at AttributesPanelWrapper (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:259186:87)
    at Image$1 (http://cdp.meiro.local:3001/static/js/vendors~main.chunk.js:260553:94)
  ```

**Comment by m-Ryan** [comment]
Please try

```tsx
const onUploadImage = async (blob: Blob) => {
    return Promise.resolve("http://res.cloudinary.com/dwkp0e1yo/image/upload/v1666623716/dfhazf4gj4wpcoe406ul.png")
  }

```

**Comment by ketys-from-meiro** [comment]
@m-Ryan oh god, dumb question, sorry
