### ISSUE TITLE
Error using useBlock indide the Demo app

### ISSUE THREAD

**Issue by keyone-zen** [zalify/easy-email#333]
I'm running the demo app and I'm trying to log the changes on any change that happens inside the editor

but I'm getting this error

```
Uncaught Error: useFormState must be used inside of a <Form> component
    at useForm (react-final-form.es.js:296:11)
    at useFormState (react-final-form.es.js:308:14)
    at useEditorContext (useEditorContext.ts:7:21)
    at useBlock (useBlock.ts:26:7)
    at App (App.tsx:13:30)
    at renderWithHooks (react-dom.development.js:14985:18)
    at mountIndeterminateComponent (react-dom.development.js:17811:13)
    at beginWork (react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
useForm @ react-final-form.es.js:296
useFormState @ react-final-form.es.js:308
useEditorContext @ useEditorContext.ts:7
useBlock @ useBlock.ts:26
App @ App.tsx:13
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback2 @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
(anonymous) @ main.tsx:15
react-dom.development.js:20085 The above error occurred in the <App> component:

    at App (http://localhost:3000/src/App.tsx?t=1689332387503:31:7)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback2 @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
(anonymous) @ main.tsx:15
react-final-form.es.js:296 Uncaught Error: useFormState must be used inside of a <Form> component
    at useForm (react-final-form.es.js:296:11)
    at useFormState (react-final-form.es.js:308:14)
    at useEditorContext (useEditorContext.ts:7:21)
    at useBlock (useBlock.ts:26:7)
    at App (App.tsx:13:30)
    at renderWithHooks (react-dom.development.js:14985:18)
    at mountIndeterminateComponent (react-dom.development.js:17811:13)
    at beginWork (react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)

```

```
import Page from '@demo/components/Page';
import store from '@demo/store';
import '@demo/styles/common.scss';
import React, { Suspense, useEffect } from 'react';
import { Provider } from 'react-redux';
import { Route, Router, Switch } from 'react-router-dom';
import { useBlock } from '../../packages/easy-email-editor/src/hooks/useBlock';
import { history } from './utils/history';

const Editor = React.lazy(() => import('@demo/pages/Editor'));

function App() {
  const { values, change } = useBlock();

  // Log the changes whenever a block value is changed
  useEffect(() => {
    console.log('Block values changed:', values);
  }, [values]);

  return (
    <Provider store={store}>
      <Page>
        <Suspense
          fallback={
            <div
              style={{
                width: '100vw',
                height: '100vh',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <img
                width='200px'
                src='/loading'
                alt=''
              />
              <p
                style={{
                  fontSize: 24,
                  color: 'rgba(0, 0, 0, 0.65)',
                }}
              >
                Please wait a moment.
              </p>
            </div>
          }
        >
          <Router history={history}>
            <Switch>
              <Route
                path='/'
                exact
                component={Editor}
              />
              <Route
                path='/editor'
                component={Editor}
              />
            </Switch>
          </Router>
        </Suspense>
      </Page>
    </Provider>
  );
}

export default App;
```

**Comment by m-Ryan** [comment]
To use useBlock, it must be used within the context of EditorProvider.
