### ISSUE TITLE
Export MUML, JSON and NHTML  doesn't work ind DEMO installation

### ISSUE THREAD

**Issue by MichaelJumble** [zalify/easy-email#369]
Perform the Demo - Example here but Export/Save does not work. HTML,, MUML, JSON will not export in local File. No PupUp appears.
Export Image works fine. Console logs:

> index.tsx:380 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at onExportMJML (index.tsx:380:25)
    at onClick (index.tsx:607:46)
    at menuItemClickHandler (item.js:54:24)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:25)
    at executeDispatch (react-dom.development.js:8243:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:7)
    at processDispatchQueue (react-dom.development.js:8288:5)

**Comment by m-Ryan** [comment]
It is not reproduced on the demo website
